version: '3'
services:
  app:
    build: app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh
    command: node index.js
    networks:
      - nodenet
    ports:
      - "3000:3000"
    volumes:
      - /app:/app
    depends_on:
      - db
  db: 
    container_name: db
    build: db
    command: --innodb-use-native-aio=0
    restart: always
    networks:
      - nodenet
  nginx:
    container_name: nginx
    build: nginx
    restart: always
    ports:
        - "8080:80"
    networks:
      - nodenet
networks:
  nodenet:
    driver: bridge  
